proto/Events/DiadocMessage-GetApi.proto
src/main/java/Diadoc/Api/DiadocApi.java
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java

Добавил новые значения в enum: MoveDocument (на самом деле старое значение, просто почему-то не добавленное) и ResolutionChainAssignment
Удалил использования метода String.isEmpty() (https://github.com/diadoc/diadocsdk-java/issues/13)

added new AttachmentType values + removed String.isEmpty()

---

src/main/java/Diadoc/Api/DiadocApi.java

add shelf download api method

---

proto/Events/DiadocMessage-PostApi.proto
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_PostApiProtos.java

Отправка зашифрованных документов в формате УПД.

Encrypted UTD/UCD support

---

proto/Docflow/DocumentInfo.proto
proto/Documents/BilateralDocument.proto
src/main/java/Diadoc/Api/Proto/Docflow/DocumentInfoProtos.java
src/main/java/Diadoc/Api/Proto/Documents/BilateralDocument/BilateralDocumentProtos.java
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java

В актах и торгах форматов 155 и 551/552 появилась возможность создавать исправления.

extend contract for Bilateral documents. Added optional revision date/number

---

proto/CloudSign.proto
src/main/java/Diadoc/Api/Proto/CloudSignProtos.java

Properties were confused
Copy of #77

fix AutosignReceiptsResult proto contract

---

proto/Events/DiadocMessage-GetApi.proto
proto/Events/DiadocMessage-PostApi.proto
proto/Invoicing/InvoiceInfo.proto
src/main/java/Diadoc/Api/DiadocApi.java
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_PostApiProtos.java
src/main/java/Diadoc/Api/Proto/Invoicing/InvoiceInfoProtos.java

* optional documentVersion to GenerateTovTorg551XmlForBuyer
* TaxedByAgent to TaxRate, fix versions
* Labels
* EditingSettingId to TemplateDocumentAttachment

Added new features

---

proto/Docflow/DocflowV3.proto
src/main/java/Diadoc/Api/Proto/Docflow/DocflowV3Protos.java

add plain text field and regenerate proto files

Add plain texts to Docflow v3

---

proto/Events/DiadocMessage-GetApi.proto
proto/Events/DiadocMessage-PostApi.proto
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_PostApiProtos.java

Add proxy to Template

---

proto/CertificateInfoV2.proto

DDCORE-6391 Add SubjectType in CertificateInfoV2

add SubjectType in CertificateInfoV2

---

src/main/java/Diadoc/Api/powersOfAttorney/PowerOfAttorneyClient.java

Добавлен потерянный параметр boxId

---

pom.xml
proto/Events/DiadocMessage-GetApi.proto
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java
src/main/java/Diadoc/Api/events/DocumentDirection.java
src/main/java/Diadoc/Api/events/EventsClient.java
src/main/java/Diadoc/Api/events/MessageType.java
src/main/java/Diadoc/Api/events/OrderBy.java

Добавлен клиент для метода /V7/GetNewEvents  
Обновлена модели DiadocMessage-GetApi

/V7/GetNewEvents  

---

proto/Events/DiadocMessage-GetApi.proto
src/main/java/Diadoc/Api/Proto/Events/DiadocMessage_GetApiProtos.java
src/main/java/Diadoc/Api/events/DocumentDirection.java
src/main/java/Diadoc/Api/events/EventsClient.java
src/main/java/Diadoc/Api/events/MessageType.java
src/main/java/Diadoc/Api/events/OrderBy.java

PullRequest сделан для удобства проверки добавления ровно этого метода /V7/GetNewEvents
Мержиться в мастер будет ветка [functional-update](https://github.com/diadoc/diadocsdk-java/tree/functional-update)

DDCORE-9513 /V7/GetNewEvents  added

---

src/main/java/Diadoc/Api/document/DocumentClient.java

PullRequest сделан для удобства проверки добавления ровно этого метода /Restore
Мержиться в мастер будет ветка [functional-update](https://github.com/diadoc/diadocsdk-java/tree/functional-update)

DDCORE-9514 Restore

---

src/main/java/Diadoc/Api/message/MessageClient.java

PullRequest сделан для удобства проверки добавления ровно этого метода /SendFnsRegistrationMessage
Мержиться в мастер будет ветка [functional-update](https://github.com/diadoc/diadocsdk-java/tree/functional-update)

DDCORE-9517 /SendFnsRegistrationMessage

---

src/main/java/Diadoc/Api/helpers/Tools.java
src/main/java/Diadoc/Api/template/TemplateClient.java

в /PostTemplatePatch добавлен operationId

DDCORE-9512 fix /PostTemplatePatch

---

src/main/java/Diadoc/Api/document/DocumentClient.java

в /PrepareDocumentsToSign добавлен excludeContent

DDCORE-9506 fix /PrepareDocumentsToSign

---

src/main/java/Diadoc/Api/document/DocumentClient.java
src/main/java/Diadoc/Api/document/DocumentsFilter.java
src/main/java/Diadoc/Api/helpers/Tools.java

В /GetDocument добавила injectEntityContent и в  /GetDocuments fromDepartmentId, toDepartmentId

DDCORE-9510 fix  /GetDocument и  /GetDocuments

---

src/main/java/Diadoc/Api/counteragent/CounteragentClient.java
src/main/java/Diadoc/Api/counteragent/CounteragentStatus.java
src/main/java/Diadoc/Api/helpers/Tools.java

в /GetCounteragents добавлены query и pageSize

DDCORE-9508 fix /V3/GetCounteragents

---

src/main/java/Diadoc/Api/DiadocApi.java
src/main/java/Diadoc/Api/auth/AuthenticateClient.java
src/main/java/Diadoc/Api/counteragent/CounteragentClient.java
src/main/java/Diadoc/Api/docflow/DocflowClient.java
src/main/java/Diadoc/Api/documentType/DocumentTypeClient.java
src/main/java/Diadoc/Api/events/EventsClient.java
src/main/java/Diadoc/Api/generateTitle/GenerateClient.java
src/main/java/Diadoc/Api/organizations/OrganizationClient.java
src/main/java/Diadoc/Api/parse/ParseClient.java
src/main/java/Diadoc/Api/shelf/ShelfClient.java
src/main/java/Diadoc/Api/sign/DiadocCloudCryptErrorCodes.java
src/main/java/Diadoc/Api/sign/SignClient.java
src/main/java/Diadoc/Api/template/TemplateClient.java
src/main/java/Diadoc/Api/user/UserClient.java

Добавила java-docи для [устаревших методов](https://developer.kontur.ru/docs/diadoc-api/index_obsolete.html)  и [удаляемых методов](https://developer.kontur.ru/docs/diadoc-api/index_removal.html)

DDCORE-9425 Добавление java-docов об устаревании

---

pom.xml
src/main/java/Diadoc/Api/message/MessageClient.java

Вместо documentId передавался entityId

DDCORE-9509 Исправить параметр в Delete

---

pom.xml
src/main/java/Diadoc/Api/message/MessageClient.java

Синхронизация с [релизом](https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F3.25.3)

entityId -> documentId

---

pom.xml
src/main/java/Diadoc/Api/CertificateHelper.java
src/main/java/Diadoc/Api/auth/AuthenticateClient.java
src/main/java/Diadoc/Api/auth/oidc/OidcAuthenticateClient.java
src/main/java/Diadoc/Api/crypt/exceptions/CertificateNotFoundException.java

1.Подтверждение токена аутентификации с помощью отпечатка вместо тела сертификата.
2. Исправление невозможности подтвердить сертификат вручную

Аутентификация

---

pom.xml
src/main/java/Diadoc/Api/CertificateHelper.java
src/main/java/Diadoc/Api/auth/AuthenticateClient.java
src/main/java/Diadoc/Api/auth/oidc/OidcAuthenticateClient.java
src/main/java/Diadoc/Api/crypt/exceptions/CertificateNotFoundException.java

1.Подтверждение токена аутентификации с помощью отпечатка вместо тела сертификата.
2. Исправление невозможности подтвердить сертификат вручную

Аутентификация proto 4

---

pom.xml
proto/PowersOfAttorney/PowerOfAttorneyValidation.proto
src/main/java/Diadoc/Api/Proto/PowersOfAttorney/PowerOfAttorneyValidationProtos.java
src/main/java/Diadoc/Api/powersOfAttorney/PowerOfAttorneyClient.java

Add prevalidatePowerOfAttorneyV2

DDCORE-10350: add V2 version PrevalidatePowerOfAttorney method
